spring:
  application:
    name: "konfi"
  datasource:
    url: jdbc:postgresql://localhost:5432/konfi_db
    username: admin
    password: admin
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always